### ISSUE TITLE
Not work in Node + React Application

### ISSUE THREAD

**Issue by drveresh** [davidcalhoun/little-time#1]
Getting the error:
little-time.js:107 Uncaught ReferenceError: context is not defined

Usage:
import littleTime from 'little-time';
//OR/AND
var littleTime = require('little-time');
...

<div>{littleTime(new Date(), 'dd-mm-yyyy hh:MM:ssTT', true)}</div>

**Comment by davidcalhoun** [comment]
Doh, sorry about that - looks like it was caused by my recent changes.  Looking into it now.

**Comment by davidcalhoun** [comment]
Ok, just released some major fixes for that error and some other stuff.  The syntax has changed a lot now - you'll want to use this syntax instead:

littleTime.utc().format('DD-MM-YYYY hh:mm:ssA')

Thanks for using the library!

**Comment by drveresh** [comment]
Thanks for the quick fix and I will give a try soon, meanwhile I got the similar solution from moment.js API.
